INSERT INTO natures
VALUES
(1, 'Performance', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Security', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Unit level', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Funcional', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Usability', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Syntax', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Compatibility', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'Logic', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)