INSERT INTO priorities
VALUES
(1, 'Low-priority', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Medium-priority', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'High-priority', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Urgent', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)