INSERT INTO resolutions
VALUES
(1, 10, 'New, not ready for development', 'Use to file a bug without all the needed information (for instance, trace files from the customer), to inform Development that a bug will soon become Status 11.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 11, 'Assigned to Development', 'Use to indicate that the bug is ready for Development, or to indicate that additional required information has been provided for a Status 30 bug', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 30, 'More Info Required. To Filer', 'Use to request more information from the bug filer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 31, 'Could Not Reproduce. To Filer', 'Use to notify filer that bug cannot be reproduced', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 32, 'Not a Bug. To Filer', 'Use to notify filer that bug was not valid', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 33, 'Suspended, Req´d Info not Avail', 'Use to notify filer that the work has been suspended until info is received', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 35, 'To Filer for Review', 'Use to request verification of the bug fix from bug filer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 36, 'Duplicate Bug. To Filer', 'Use to respond to filer that the bug is a duplicate', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 39, 'Approved, waiting for codeline to open', 'Use to indicate that a backport has been approved and is waiting for codeline to open. When the codeline is opened, status will be changed to 40', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 40, 'Waiting for the base bug fix', 'Use to show that bug is waiting for another bug to be fixed', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 45, 'Vendor OS Problem, to Filer', 'Use when an operating system problem is the cause of the bug, to indicate that, following verification, bug filer should update to Status 95', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 60, 'CM: Awaiting Promote', 'Configuration Management: Use to indicate that the fix has been developed and is awaiting promotion to the TEST environment', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 66, 'CM: Awaiting Deployment', 'Configuration Management : Use to indicate that the fix has been tested and is awaiting a patch or release', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 70, 'Closed, data fix, cause - user error', 'Applications: Use when the user performed an illegal operation, such as directly updating data using PL/SQL. This includes bad data being populated by custom code. This caused the data to be inconsistent and required that the data be fixed using a data fix script', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 71, 'Closed, data fix, cause - data import', 'Applications: Use when bad data was imported into the system, either via automated batch load, or as the result of data conversion during the installation of the product. This caused the data to be inconsistent and required that the data be fixed using a data fix script', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 72, 'Closed, data fix, cause - code error', 'Applications: Use when bad data was populated into the database due to an error in supported software. This caused the data to be inconsistent and required that the data be fixed using a data fix script', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 73, 'Closed, data fix, cause - unknown', 'Applications : Use when bad data was found to exist in the customers database, which required that the data be fixed using a data fix script. The root cause was never determined', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 74, 'Closed, Verified by QA', 'Applications : Use to close bugs verified by Quality Assurance team', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 75, 'Closed, Not Verified by QA', 'Use to indicate that a fix is available, but the code has not being verified by Quality Assurance', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 83, 'Closed, Product/Platform', 'Use to close a bug that was not fixed because of product or platform obsolescence', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 84, 'Closed, not feasible to fix', 'Use to close a bug that was not fixed because the fix was not feasible', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 91, 'Closed, could not reproduce', 'Use to close a bug that development could not reproduce', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 92, 'Closed, not a bug', 'Use to close a bug that was not a bug', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 95, 'Closed, Vendor OS Problem', 'Use to close a bug that is a vendor operating system problem', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 96, 'Closed, duplicate bug', 'Use to close a bug that is a duplicate of another bug', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)