INSERT INTO severities
VALUES
(1, 'Critical', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Major', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Normal', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Minor', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Trivial', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Enhancement', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)